title: FEZ Modding Wiki
description: Collection of resources for FEZ modding. 

readme_index:
  with_frontmatter: true

permalink: /:categories/:title

# original: rundocs/jekyll-rtd-theme
# identical? fork 1: bxthomas/jekyll-rtd-theme
# identical? fork 2: amkherad/jekyll-rtd-theme
remote_theme: bxthomas/jekyll-rtd-theme

toc: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
